Deps/update to decidim 0 26
Platoniq/decidim-coincidim pull request #48
Opened 2022-03-14 09:46 UTC by agustibr

- [ ] webpack stuff
- [ ] styles working
- [ ] javascript working
- [ ] Mailing
- [ ] Overrides checks
- [ ] Tests
- [ ] API /graphql

2022-03-15 10:18 UTC, microstudi requested changes
Thanks @agustibr 
I think there's only one thing that needs to be changed related to the use of image_pack_tag.

As per the assets definition, there's an alternative approach that can be used if you prefer it (done it in https://github.com/Platoniq/decidim-indices/tree/main/app/packs)

2022-03-15 10:18 UTC, microstudi commented on app/views/layouts/platoniq/_mini_footer.html.erb
> +          <%= image_pack_tag current_organization.official_img_footer.url.to_s , alt: current_organization.name %>
```suggestion
<% if current_organization.official_img_header.attached? %>
        <%= image_tag current_organization.attached_uploader(:official_img_header).path, class: "minimap-official_img_header" %>
      <% else %>
        <span class="float-right"><%= t("official_img_header", scope: "activemodel.attributes.organization") %> &gt; </span>
        <%= content_tag :div, nil, { class: "minimap-official_img_header placeholder float-right", style: "width: #{image_width(current_organization, :official_img_header) * size_factor }px; height: #{image_height(current_organization, :official_img_header) * size_factor }px;" } %>
      <% end %>
```

image_pack_tag can only be used for static assets. Check this example https://github.com/decidim/decidim/blob/c9ed6740e8025fd482b49dad71cc1788b5e572c0/decidim-admin/app/views/decidim/admin/organization_appearance/form/_minimap.html.erb

2022-03-15 10:18 UTC, microstudi commented on config/assets.rb
> +Decidim::Webpacker.register_stylesheet_import("stylesheets/coincidim")
There's an alternative to this (and this file can be empty).
Require the endpoints in the default file for a decidim application, like don in here:
https://github.com/Platoniq/decidim-indices/blob/main/app/packs/stylesheets/decidim/decidim_application.scss

2022-03-15 10:18 UTC, microstudi commented on config/initializers/decidim.rb
> +
```suggestion
Rails.application.config.to_prepare do
  # Api tunnings
  Decidim::Api::Schema.max_complexity = 5000
  Decidim::Api::Schema.max_depth = 50
end
```
Can you add this? nothing related to the update but needed to make the awesome map work properly

2022-03-15 10:23 UTC, agustibr commented
Thanks @microstudi for the review, I'll push the suggested changes and ping you back later 😄

2022-03-17 09:23 UTC, microstudi requested changes
ok, everything looks good.

There's only one thing missing, email customization.

Emails look like this in the original coincidim:
![image](https://user-images.githubusercontent.com/1401520/158777914-3a0e5f52-550e-4f94-9e0a-5a84c39c2ffc.png)

Indices is also customized, so we should review how it's done there:
![image](https://user-images.githubusercontent.com/1401520/158778296-0d283e74-c4d3-4ca6-a690-ac13ce6e4966.png)

2022-03-18 08:07 UTC, agustibr commented
Thanks for the heads up @microstudi 😁  

The email customization is fixed now!

This is how the email is rendered _locally_:

![Screenshot from 2022-03-18 09-00-37](https://user-images.githubusercontent.com/210216/158960892-99d18034-dce2-44f3-bfa5-7f54a19ee111.png)

2022-03-18 10:37 UTC, microstudi approved these changes
Perfec @agustibr 
thanks on this one!

2022-03-18 10:38 UTC, merged